# Generated by Django 4.2.7 on 2024-01-12 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_restaurant_business_whatsapp_country_code_and_more'),
        ('owner_dashboard', '0002_remove_restaurantnotification_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_queries', to='core.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
