# Generated by Django 4.2.7 on 2024-01-12 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner_dashboard', '0003_publicquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicquery',
            name='raise_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
