# Generated by Django 4.2.7 on 2024-02-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_dashboard', '0004_publicquery_raise_by'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publicquery',
            index=models.Index(fields=['restaurant'], name='owner_dashb_restaur_5d2c20_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantnotification',
            index=models.Index(fields=['restaurant'], name='owner_dashb_restaur_6095e4_idx'),
        ),
    ]
