# Generated by Django 4.2.7 on 2024-03-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_country_requestdetailsupdate_address_ru_and_more'),
        ('owner_dashboard', '0005_publicquery_owner_dashb_restaur_5d2c20_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotion_images')),
                ('apply_on_everyday', models.BooleanField(default=False)),
                ('offer_start_time', models.TimeField(blank=True, null=True)),
                ('offer_end_time', models.TimeField(blank=True, null=True)),
                ('term_and_condition', models.TextField(blank=True, null=True)),
                ('offer_type', models.CharField(choices=[('percentage', 'percentage'), ('fixed_amount', 'fixed_amount'), ('bogo', 'bogo')], max_length=20)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionWeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_days', to='owner_dashboard.promotion')),
            ],
            options={
                'indexes': [models.Index(fields=['promotion'], name='owner_dashb_promoti_49353b_idx')],
                'unique_together': {('promotion', 'day')},
            },
        ),
        migrations.CreateModel(
            name='PromotionOnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.menuitem')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicable_on', to='owner_dashboard.promotion')),
            ],
            options={
                'indexes': [models.Index(fields=['promotion'], name='owner_dashb_promoti_1c995c_idx')],
                'unique_together': {('promotion', 'item')},
            },
        ),
    ]
