# Generated by Django 4.2.7 on 2024-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_dashboard', '0006_promotion_promotionweekday_promotiononitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
