# Generated by Django 4.2.7 on 2023-11-08 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetConfirmation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pass_reset_confirmation', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_end_user',
        ),
    ]
