# Generated by Django 4.2.7 on 2023-11-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetconfirmation_remove_user_is_end_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
