# Generated by Django 4.2.7 on 2023-11-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_twofactorverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
