# Generated by Django 4.2.7 on 2023-11-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country_code',
        ),
    ]
