# Generated by Django 4.2.7 on 2023-12-13 08:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=users.models.collaborator_profile_pic_dir)),
                ('description', models.TextField(blank=True, null=True)),
                ('whatsapp_country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('youtube_channel_link', models.TextField(blank=True, null=True)),
                ('fb_profile_link', models.TextField(blank=True, null=True)),
                ('insta_profile_link', models.TextField(blank=True, null=True)),
                ('twitter_profile_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
