# Generated by Django 4.2.7 on 2023-12-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
