# Generated by Django 4.2.7 on 2024-01-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_collaborator_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cafe_manager',
            field=models.BooleanField(default=False),
        ),
    ]
