# Generated by Django 4.2.7 on 2024-01-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_is_cafe_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_visitor',
            field=models.BooleanField(default=False),
        ),
    ]
