# Generated by Django 4.2.7 on 2024-01-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='whatsapp_country_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country_code',
        ),
    ]
