# Generated by Django 4.2.7 on 2023-11-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adsbanner_alter_menuitemimages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
