# Generated by Django 4.2.7 on 2023-11-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_alter_restaurant_name_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
