# Generated by Django 4.2.7 on 2023-11-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restaurantcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbanner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
