# Generated by Django 4.2.7 on 2023-11-30 05:15

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_adsbanner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.restaurant_profile_pic_dir),
        ),
        migrations.CreateModel(
            name='RestaurantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=core.models.restaurant_pic_dir)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_images', to='core.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
