# Generated by Django 4.2.7 on 2023-11-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_restaurant_profile_image_restaurantimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
