# Generated by Django 4.2.7 on 2023-12-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_whatsapp_country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
