# Generated by Django 4.2.7 on 2023-12-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_restauranttimings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttimings',
            name='from_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restauranttimings',
            name='to_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
