# Generated by Django 4.2.7 on 2023-12-21 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemimages',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_images', to='core.menuitem'),
        ),
    ]
