# Generated by Django 4.2.7 on 2023-12-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_menuitemimages_menu_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantcategory',
            unique_together={('category', 'restaurant')},
        ),
    ]
