# Generated by Django 4.2.7 on 2024-01-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_clamrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clamrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
