# Generated by Django 4.2.7 on 2024-01-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_clamrequest_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='business_whatsapp_country_code',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='country_code',
        ),
    ]
