# Generated by Django 4.2.7 on 2024-01-19 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_restaurant_business_whatsapp_country_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantservice',
            unique_together={('service', 'restaurant')},
        ),
    ]
