# Generated by Django 4.2.7 on 2024-02-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_review_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report_rejected',
            field=models.BooleanField(default=True),
        ),
    ]
