# Generated by Django 4.2.7 on 2024-02-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_review_report_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='report_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
