# Generated by Django 4.2.7 on 2024-02-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_review_report_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
