# Generated by Django 4.2.7 on 2024-02-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_requestdetailsupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['restaurant'], name='core_favori_restaur_8fa634_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='core_favori_user_id_cbe902_idx'),
        ),
        migrations.AddIndex(
            model_name='itemingredient',
            index=models.Index(fields=['item'], name='core_itemin_item_id_72acf4_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant'], name='core_menuit_restaur_119519_idx'),
        ),
        migrations.AddIndex(
            model_name='qa',
            index=models.Index(fields=['restaurant'], name='core_qa_restaur_4d7e31_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['owner'], name='core_restau_owner_i_76aa42_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='core_restau_name_aa744f_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantacceptedpayment',
            index=models.Index(fields=['restaurant'], name='core_restau_restaur_fb26b5_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantcategory',
            index=models.Index(fields=['restaurant'], name='core_restau_restaur_55984b_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantimages',
            index=models.Index(fields=['restaurant'], name='core_restau_restaur_984b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantservice',
            index=models.Index(fields=['restaurant'], name='core_restau_restaur_8cdec8_idx'),
        ),
        migrations.AddIndex(
            model_name='restauranttimings',
            index=models.Index(fields=['restaurant'], name='core_restau_restaur_793a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['restaurant'], name='core_review_restaur_27ddd9_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category'], name='core_subcat_categor_c2fc1d_idx'),
        ),
    ]
