# Generated by Django 4.2.7 on 2024-03-13 04:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_businesstype_city_restaurantcuisines_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.category_images_dir),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.sub_category_images_dir),
        ),
    ]
