# Generated by Django 4.2.7 on 2024-03-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_restaurant_business_2gis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstype',
            name='type',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='modeofpayment',
            name='payment_name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.TextField(unique=True),
        ),
    ]
