# Generated by Django 4.2.7 on 2024-03-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_businesstype_type_alter_city_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdetailsupdate',
            old_name='country',
            new_name='address_ru',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='country',
        ),
        migrations.AlterField(
            model_name='requestdetailsupdate',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_restaurants_update', to='core.city'),
        ),
        migrations.AlterField(
            model_name='requestdetailsupdate',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_restaurants_update', to='core.state'),
        ),
    ]
