# Generated by Django 4.2.7 on 2024-03-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_country_requestdetailsupdate_address_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutype',
            name='type',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
