# Generated by Django 4.2.7 on 2024-06-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_menutype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbanner',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_ads_banner', to='core.restaurant'),
        ),
    ]
