# Generated by Django 4.2.7 on 2024-02-07 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDisputeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('query', models.TextField()),
                ('replay', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('query_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dispute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
