# Generated by Django 4.2.7 on 2024-05-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_event_participant_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='social_even_restaur_9486d4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='is_approved_by_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
